[supabase]
url = "https://tbovauczjolatzumiodx.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRib3ZhdWN6am9sYXR6dW1pb2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDQ4MjQsImV4cCI6MjA2NTg4MDgyNH0.42u6u8m0qFbEzSq9Znncooqpm_EsHPRDi4W0iiS90gE"
